name: "build-and-deploy-site"
on:
  push:
    branches:
      - publish

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCE_PROJECT }}
        service_account_key: ${{ secrets.GCE_SA_KEY }}
    - run: |
        npm ci
        npm install -g gatsby-cli
        gatsby build
        ls $GITHUB_WORKSPACE
        gsutil rsync -r $GITHUB_WORKSPACE/public ${{ secrets.GS_BUCKET }}
