name: "build-and-deploy-site"
on:
  push:
    branches:
      - publish

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - run: |
        npm ci
        gatsby build
        gcloud config set project ${{ secrets.GCE_PROJECT }}
        gsutil rsync -r $GITHUB_WORKSPACE/public ${{ secrets.GS_BUCKET }}
