name: "build-and-deploy-site"
on:
  push:
    branches:
      - publish

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '15'
    - name: install deps
      run: npm ci
      run: gatsby build
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCE_SA_KEY }}
    - run: |
        gcloud config set project ${{ secrets.GCE_PROJECT }}
        gsutil rsync -r $GITHUB_WORKSPACE/_site ${{ secrets.GS_BUCKET }}
